POST http://localhost:5400/api/user
Content-Type: application/json

{
    "Nom":"Lagna",
    "Prenom":"Antoine",
    "Email":"lagna.antoine@gmail.com",
    "Pays":"Afghanistan",
    "Telephone":"0497318439",
    "Password":"937e8d5fbb48bd4949536cd65b8d35c426b80d2f830c5c308e2cdec422ae2244",
    "isAdmin":false,
    "Token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImxhZ25hLmFudG9pbmVAZ21haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTYzNzkzNDY2OX0.zsrNpXsK-VqxQTvqTS4SOiXw2bENUzKshbs1xwtG1pU"
}
###

DELETE http://localhost:5400/api/user/lagna.antoine@gmail.com


###
POST http://localhost:5400/api/login
Content-Type: application/json

{
    "Email": "van.bellinghen.brian@gmail.com",
    "Password": "24605b48ed8e0fbb239979a42f01f9af97031551a688bd70bd60765b280f3169"
}

###
PUT http://localhost:5400/api/user/lagna.antoine@gmail.com
Content-Type: application/json

{
    "Nom": "Lagna",
    "Prenom": "Antoine",
    "Email": "lagna.antoine@gmail.com",
    "Pays": "Afghanistan",
    "Telephone": "0497318439",
    "Password": "937e8d5fbb48bd4949536cd65b8d35c426b80d2f830c5c308e2cdec422ae2244",
    "isAdmin": false,
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImxhZ25hLmFudG9pbmVAZ21haWwuY29tIiwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTYzNzkzNzQzMn0.-oGW3lJ3AMd7RObBBLPldEocbvXuQAw5uhF9pUDE5GY"
}